---
language: python
python: "2.7"

before_install:
  # Update all packages
  - sudo apt-get update -qq

install:
  # Install Ansible
  - pip install ansible

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
